name: DJANGO application

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pipenv==2020.11.15
        pipenv sync --dev
    - name: Test with pytest
      run: |
        pipenv run pytest --cov=../jogo_magico
    - name: Posting Coverage
      env:
        CODECOV_TOKEN: "9e55c584-58f7-4553-936a-7b9b8e2e3223"
      run: |
        pipenv run codecov
